### ISSUE TITLE
Add convenience method for running compiled function (`ExecutableModule`) with given arg(s)

### ISSUE THREAD

**Issue by Boscop** [slowli/arithmetic-parser#10]
In my use case I need to evaluate a program to an owned expression (`'static`), cache it (as `ExecutableModule`) and evaluate it later many times (the expr is a function, basically `f32 -> f32`).
Currently I'm injecting the `x` variable as an import on every call, representing the arg:
```rust
			expr.set_import("x", Value::Number(x));
			match expr.run() {
				Ok(ret) => {
					if let Value::Number(val) = ret {
						val
					} else {
						panic!("expected number, got: {:?}", ret);
					}
				}
				Err(e) => panic!("eval failed: {}", e.source()),
			}
```
But there are 2 issues with this:
1. I need to mutate the `ExecutableModule` for every call, even though it should represent a pure function
2. It assumes that the function wants to call its arg `x` and doesn't let the decision to the author of the code (it's read from a config file) and it should be the author of the code who gets to name the arg.

Ideally, the expr should represent a function, and I wouldn't call `expr.set_import("x", Value::Number(x))` but `expr.call(Value::Number(x))`, passing `x` as arg without mutating the module.

So I'm suggesting adding a method `ExecutableModule::call` for use cases like this.

If this was possible, it would fix half of https://github.com/slowli/arithmetic-parser/issues/7

**Comment by slowli** [comment]
@Boscop Not a solution, but rather a suggestion possibly allowing to sidestep the issue. If the module evaluates to a function, then it is possible to evaluate the module once to get this function, and then evaluate *it*, rather than the module. That is, rather than having module

```text
sin(x) + 3*cos(x)
```

this method will have a module

```text
|x| { sin(x) + 3*cos(x) }
```

(`sin` and `cos` functions are here just to demonstrate that the function returned from the module may capture environment).

**Comment by Boscop** [comment]
@slowli Ok, and what should I pass for `ctx` to `evaluate`?
https://docs.rs/arithmetic-eval/0.1.0/arithmetic_eval/enum.Function.html#method.evaluate

**Comment by Boscop** [comment]
I'm now doing this: 

```rust
rental! {
	mod rentals {
		use super::*;

		#[rental]
		pub struct ExprRef {
			code: String,
			expr: InterpretedFn<'code, F32Grammar>,
		}
	}
}
// ...

	|code| {
		let mut program = rentals::ExprRef::new(code, |code| {
			match new_interpreter_with_prelude()
				.evaluate(&F32Grammar::parse_statements(Span::new(code)).unwrap())
			{
				Ok(Value::Function(Function::Interpreted(f))) => {
					Rc::try_unwrap(f).expect("one ref")
				}
				Ok(val) => panic!("expected function, got: {:?}", val),
				Err(e) => panic!("eval failed: {}, {:?}", e.source(), e.main_span()),
			}
		});

		(box move |x| {
			program.rent_mut(|expr| {
				match expr.evaluate(
					vec![SpannedValue {
						offset: 0,
						line: 0,
						fragment: "",
						extra: Value::Number(x),
					}],
					&mut CallContext::mock(),
				) {
					Ok(ret) => {
						if let Value::Number(val) = ret {
							val
						} else {
							panic!("expected number, got: {:?}", ret);
						}
					}
					Err(e) => panic!("eval failed: {:?}", e),
				}
			})
		}) as Box<dyn FnMut(f32) -> f32>
	}
```

I have a few questions:
1. Isn't it slower than executing a compiled module?
1. Do you have suggestions how I can improve the error printing to make the errors maximally helpful for the user?
1. Is it correct to use `CallContext::mock()`?
1. Is there a more convenient way to pass args, without having to construct fake spans? If not, I think it would make sense to add a convenience method that takes raw args and wraps them in fake spans, and also creates an empty `CallContext`.
1. It would be nice if the function could be called without having to allocate a `Vec`, by accepting a slice or iterator.

**Comment by slowli** [comment]
> Isn't it slower than executing a compiled module?

Honestly, both ways are quite slow compared to native code (or one generated dynamically, via a tool like [Cranelift](https://github.com/bytecodealliance/cranelift)). I didn't perform benchmarks for this case, but each interpreted function is compiled into its own module internally, so using an interpreted function should not have *that* high overhead.

Again, my suggestion is a workaround, rather than a complete solution; I fully understand this.

> Do you have suggestions how I can improve the error printing to make the errors maximally helpful for the user?

One of possibilities is to take a look at the CLI / REPL package. I think it does a passable job at reporting errors in most cases.

> Is it correct to use `CallContext::mock()`?

It depends on the use case, but it's the best possible option right now. Perhaps the largest downside of the mock context is that it does not retain a backtrace on errors.

> Is there a more convenient way to pass args, without having to construct fake spans?

No right now. I agree that it makes sense to introduce helper(s) in order to call interpreted functions in a more eloquent manner.

**Comment by slowli** [comment]
#15 has introduced `ModuleImports` as a separate entity, which allows to conveniently run the  module with different imports.
